// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iowpmgqjdiwuwpxxksdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvd3BtZ3FqZGl3dXdweHhrc2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjMyNjksImV4cCI6MjA3MjkzOTI2OX0.htx9y0heDupcNFPiUm6wr3uwqRqK9r09jjzOGIV1HRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});